mattermost/mattermost-plugin-azure-devops

server/constants/routes.go, server/plugin/api.go, server/serializers/project.go
Created plugin API to fetch linked projects list
Changes of this PR is already 1st pass reviewed here https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/10
=> [MI-1986]: Create plugin API to fetch linked projects list

server/constants/messages.go, server/constants/routes.go, server/plugin/api.go, server/serializers/common.go, webapp/src/components/card/project/index.tsx, webapp/src/components/modal/confirmationModal/index.tsx, webapp/src/containers/LinkModal/index.tsx, webapp/src/containers/Rhs/projectList/index.tsx, webapp/src/hooks/usePluginApi.ts, webapp/src/plugin_constants/index.ts, webapp/src/reducers/linkModal/index.ts, webapp/src/reducers/projectDetails/index.ts, webapp/src/selectors/index.tsx, webapp/src/services/index.ts, webapp/src/types/common/index.d.ts, webapp/src/types/common/store.d.ts
1st pass review is done here https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/17
=> [MI-2001]: Create plugin API to unlink project and integration

server/constants/messages.go, server/plugin/api.go
Already reviewed changes picked from https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/36
=> [MI-2011] Add API to listen notifications

server/constants/messages.go, server/plugin/api.go
Already approved changes picked from https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/37/files
=> [MI-2023] API to delete subscriptions

server/constants/messages.go, server/plugin/api.go
Already approved changes picked from https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/38/files
=> [MI-2029] Add feature to create subscription from modal

server/constants/constants.go, server/plugin/api.go, server/plugin/utils.go, server/store/subscriptions.go
Already approved changes https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/39
=> [MI-2030] Add filter to fetch subscriptions related to project

server/plugin/api.go
Already reviewed changes https://github.com/Brightscout/mattermost-plugin-azure-devops/pull/41/files
=> [MI-2057] Integrate subscription list page

plugin.json, webapp/src/components/modal/index.tsx, webapp/src/components/resultPanel/index.tsx, webapp/src/components/svgWrapper/index.tsx, webapp/src/containers/LinkModal/index.tsx, webapp/src/containers/SubscribeModal/index.tsx, webapp/src/plugin_constants/icons.tsx
=> [MI-2092] Add success modal to the modals

README.md, docs/developer_docs.md, docs/oauth_setup.md, docs/plugin_setup.md, plugin.json
Updated documentation for plugin phase-1
=> [MI-2125]: Updated documentation for plugin phase-1

Makefile, server/constants/constants.go, server/plugin/api.go, webapp/src/containers/Rhs/projectDetails/index.tsx, webapp/src/hooks/usePreviousState.ts, webapp/src/plugin_constants/apiService.ts, webapp/src/services/index.ts, webapp/src/types/common/index.d.ts, webapp/src/utils/filterData.ts
Moved filter on the server side to get subscriptions for the requested channel
Modified web app to support new server changes
=> [MI-2135]: Moved filter on the server side to get subscriptions for the requested channel

webapp/src/containers/modals/LinkModal/index.tsx, webapp/src/utils/errorHandling.ts
Handle error on link project modal
=> [MI-2175]: Handle error on link project modal

server/constants/constants.go, server/constants/messages.go, server/plugin/api.go, server/plugin/api_test.go, server/serializers/subscriptions.go, server/store/subscriptions.go, webapp/src/components/buttons/iconButton/index.tsx, webapp/src/components/card/subscription/index.tsx, webapp/src/components/modal/confirmationModal/index.tsx, webapp/src/components/modal/subComponents/modalSubtitleAndError/styles.scss, webapp/src/components/toggleSwitch/index.tsx, webapp/src/components/toggleSwitch/styles.scss, webapp/src/containers/Rhs/projectDetails/header.tsx, webapp/src/containers/Rhs/projectDetails/index.tsx, webapp/src/containers/modals/LinkModal/index.tsx, webapp/src/hooks/useApiRequestCompletionState.ts, webapp/src/plugin_constants/common.ts, webapp/src/plugin_constants/form.ts, webapp/src/plugin_constants/icons.tsx, webapp/src/plugin_constants/index.ts, webapp/src/plugin_constants/messages.ts, webapp/src/styles/_components.scss, webapp/src/styles/_utils.scss, webapp/src/types/common/form.d.ts, webapp/src/types/common/index.d.ts, webapp/src/types/common/payload.d.ts, webapp/src/utils/errorHandling.ts
Implemented Admin management flow for subscriptions.
=> [MI-2165]: Implemented Admin management flow for subscriptions.

server/constants/constants.go, server/constants/messages.go, server/plugin/command.go, server/plugin/utils.go, webapp/src/hooks/index.js, webapp/src/utils/index.ts
- Added flags on the server in the list subscription slash command to support filters.
- Refactored all the commands with nested sub-commands and auto-suggestions.
=> [MI-2193]: Made changes on server to support filters and refactored all the commands

plugin.json
Features in this version-
1. Added support to add/delete subscriptions for Repos via UI and slash command
2. Added support to view subscriptions of Boards and Repos together in the RHS for a project and separately using slash command
3. Enhanced slash command flow with auto suggestions
4. Enhanced management of subscriptions for admin and non-admin users
=> Bump the plugin version to v1.3.0

server/constants/messages.go, server/plugin/api.go, server/plugin/command.go, server/plugin/utils.go
Added admin constraints on slash commands for subscriptions list
=> [MI-2235][Server]: Added admin constraints on slash commands

README.md, docs/developer_docs.md
=> [MI-2177][Documentation]: Updated readme files

server/plugin/client.go, server/serializers/subscriptions.go, webapp/src/containers/modals/SubscribeModal/filters/repos.tsx, webapp/src/containers/modals/SubscribeModal/index.tsx, webapp/src/pluginConstants/apiService.ts, webapp/src/pluginConstants/form.ts, webapp/src/services/index.ts, webapp/src/types/common/form.d.ts, webapp/src/types/common/index.d.ts, webapp/src/types/common/payload.d.ts, webapp/src/types/common/service.d.ts, webapp/src/utils/index.ts
Created UI and integrated repository filter for Repos.
=> [MI-2279][webapp]: Created UI and integrated repository filter for Repos

plugin.json, server/plugin/api.go
What's new?
1. Filter to add subscriptions for a particular repository for Repos.
2. Filter to add subscriptions for a particular branch on a repository for Repos.
=> Bump plugin version to v2.1.0

mocks/mock_client.go, server/plugin/api.go, server/plugin/api_test.go, server/plugin/client.go, server/plugin/utils.go, server/serializers/subscriptions.go, server/store/subscriptions.go, server/store/subscriptions_test.go, server/store/utils.go, webapp/src/components/card/subscription/index.tsx, webapp/src/containers/Rhs/projectDetails/index.tsx, webapp/src/containers/modals/SubscribeModal/filters/boards.tsx, webapp/src/containers/modals/SubscribeModal/filters/repos.tsx, webapp/src/containers/modals/SubscribeModal/index.tsx, webapp/src/pluginConstants/apiService.ts, webapp/src/pluginConstants/common.ts, webapp/src/pluginConstants/form.ts, webapp/src/pluginConstants/index.ts, webapp/src/reducers/subscribeModal/index.ts, webapp/src/services/index.ts, webapp/src/types/common/form.d.ts, webapp/src/types/common/index.d.ts, webapp/src/types/common/payload.d.ts, webapp/src/types/common/service.d.ts, webapp/src/types/common/store.d.ts, webapp/src/utils/errorHandling.ts, webapp/src/utils/index.ts
- Made changes in plugin API for returning filter values based on different events for Repos
- Integrated UI subscription filter flow with API
-  Added conditional filters for Repos
- Added Area Path for Boards
=> [MI-2314][server+webapp]: Made changes in plugin API for returning filter values and integrated UI subscripton filter flow with API.

plugin.json, webapp/src/components/modal/subComponents/modalBody/styles.scss
Release notes-
1. Added the following filters for "Repos" subscription:
- Repository
- Target Branch
- Reviewer includes group
- Requested by a member of group
- Pushed by a member of group
- Change
- Merge result
2. Added I filter for "Boards" subscription:
- Area Path
=> Bump plugin version to v2.2.0

server/constants/oauth_config.go, server/serializers/subscriptions.go, server/store/utils.go, webapp/src/containers/Rhs/index.tsx, webapp/src/containers/modals/SubscribeModal/index.tsx, webapp/src/hooks/useForm.ts, webapp/src/pluginConstants/common.ts
1. Make api call whenever we open RHS - To update the RHS state (Issue is occuring when redux state reset on hard refresh)
2. Repos subscription for "Merge attempt" event with "Requested by member of group" filter not getting deleted after creation 
3. If we select "All" manually in the filters whose values are coming from API, it gets displayed in the subscription card chip
4. Filters value not getting reset when the eventType is changed
=> [MI-2374] Fixed bugs

server/constants/messages.go, server/plugin/client.go, webapp/src/containers/modals/SubscribeModal/index.tsx
1. On subscription modal error message is visible all the time
2. Handle refresh token expiry
=> [MI-2387] Fixed bugs in Azure DevOps

webapp/src/components/modal/subComponents/modalBody/styles.scss, webapp/src/components/modal/subComponents/modalHeader/index.tsx, webapp/src/components/modal/subComponents/modalHeader/styles.scss, webapp/src/containers/modals/SubscribeModal/index.tsx, webapp/src/containers/modals/TaskModal/index.tsx, webapp/src/styles/_components.scss
Fixed UI bugs on different versions of MM:
- "Link Project" and "Add New Subscription" buttons getting hidden on MM version "5.37.9" in RHS
- "Create Subscription" modal overflow for Repos filters on MM v6.7
=> [MI-2395][webapp]: Fix UI bugs on different versions of MM.

plugin.json
What's New?
1. Added feature to allow user delete their subscriptions for a project when unlinking it.
2. UI enhancements and bug fixes.
=> Bump plugin version to v2.2.1

server/constants/constants.go, webapp/src/containers/modals/SubscribeModal/index.tsx
Enhancement: Reset target branch value when repository value is changed to "All"
=> [MI-2416] Updated help command text for repos

server/plugin/api.go
Fixed organization name for Pipelines
=> [Fix]: Fixed organization name for Pipelines

Makefile, build/legacy.mk, plugin.json, server/plugin/manifest.go
First release to the Marketplace
- https://github.com/mattermost/mattermost-plugin-azure-devops/pull/128
=> Release v3.2.0

webapp/src/components/toggleSwitch/styles.scss
- Fixed spacing issue near toggle button
Before:
Now:
https://github.com/mattermost/mattermost-plugin-azure-devops/pull/161#issuecomment-1993866506
=> [MM-288] Fixed spacing issue near toggle button
